## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

env:
  - PYTHON=Conda  # makes PyCall.jl use Conda.jl

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PyBase"); Pkg.test("PyBase"; coverage=true)'
after_success:
  - cat Manifest.toml
  - julia --color=yes -e 'using Pkg; Pkg.add("Coverage")'
  # push coverage results to Coveralls
  - julia --color=yes -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia --color=yes -e 'using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - docs/make.jl
      after_success: skip
